### ISSUE TITLE
Update for issue #1024

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/MODxFLAT#1]
@Nicola1971 
Should this be added to address the "[Multiple Sessions](https://github.com/Deesen/evolution/commit/f8cd9832c8a574fc2a724aa713bd7a54335c058e)" fix?

welcome.tpl  line28

`<!-- logout reminder -->`
  `<div id="multiple_sessions" style="display:[+show_multiple_sessions+]">`
     `<div class="widget-wrapper alert alert-warning">`
         `[+multiple_sessions_msg+]`
      `</div>`
`</div>`

**Comment by Nicola1971** [comment]
added

**Comment by Nicola1971** [comment]
reverted because is not yet fixed/implemented in evo 1.2

**Comment by risingisland** [comment]
When is the next update coming to reflect the new style changes (filemanager, etc.)?

**Comment by Nicola1971** [comment]
modxflat dev for nex version of evo is here https://github.com/Nicola1971/MODxFLAT/tree/dev

**Comment by risingisland** [comment]
Thanks Nicola.

**Comment by risingisland** [comment]
File: welcome.tpl
Line: 232
Has one additional start bracket: `[[(site_name:encode_js)]`

**Comment by Nicola1971** [comment]
fixed

https://github.com/Nicola1971/MODxFLAT/commit/7c95b74238ce59748eb02be3fc27edd55fd0b72e
