### ISSUE TITLE
login.tpl lang.?

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/MODxFLAT#3]
Should line 2 of login.tpl:
`<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">`
be changed to...
`<html xmlns="http://www.w3.org/1999/xhtml" lang="[(lang_code)]" xml:lang="[(lang_code)]">`

**Comment by Nicola1971** [comment]
added in latest build, thanks
