### ISSUE TITLE
Weblink field width and search text

### ISSUE THREAD

**Issue by bossloper** [Nicola1971/MODxFLAT#4]
With the new 'Insert' button for weblinks the button and help icon wrap to the next line.
The current 1.2.1 has this as a compromise (I couldn't get them to line up so made it obvious it was not trying to!):
https://github.com/modxcms/evolution/blob/develop/manager/media/style/MODxRE2/style.css#L2167-L2169

![untitled](https://cloud.githubusercontent.com/assets/1744687/21929525/d97a7d20-d988-11e6-9b46-5917691d2845.png)

Also would suggest the search text needs more contrast (lighter):
![u1](https://cloud.githubusercontent.com/assets/1744687/21929466/89e59466-d988-11e6-832f-0a3a379f56c9.png)

**Comment by Nicola1971** [comment]
thanks. added to master (now official version for 1.2.1)

search placeholder text color need more fix for firefox (new color works only on chrome)
