### ISSUE TITLE
Update for v1.2.2?

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/MODxFLAT#6]
Any chance of an update for the new buttons etc. in v1.2.2, maybe as a dev. release as 1.2.2 is still beta?

**Comment by Nicola1971** [comment]
yes, i've started the new Flat beta for 1.2.2 - just wait some days when new new manage elements features will be merged to the evo dev branch

https://github.com/modxcms/evolution/pull/1235

**Comment by risingisland** [comment]
Nice, looking forward to both. Thanks

**Comment by Nicola1971** [comment]
New version for evolution cms 1.4 here: https://github.com/Nicola1971/EvoFLAT

**Comment by risingisland** [comment]
Awesome Nicola, I will try to test this today if I can. Thanks for heads up.
 

    On Monday, October 9, 2017, 10:58:35 AM GMT+1, Nicola <notifications@github.com> wrote:  
 
 
New version for evolution cms 1.4 here: https://github.com/Nicola1971/EvoFLAT
